### ISSUE TITLE
Zmniejszenie liczby kolumn w ramce danych

### ISSUE THREAD

**Issue by ZuzannaKozyra** [adamAfro/hereishouse#13]
Decyzja o tym , które zostawiamy, a które zliczmy do jednej kolumny

**Comment by adamAfro** [comment]
Zamiana na binarne, bo nie som, a powinny być niektóre

```py
# Znajdź kolumny, które mają tylko jedną unikalną wartość
single_value_columns = df.columns[df.nunique() == 1]

# Zamień te kolumny na binarne, gdzie NaN jest False
for col in single_value_columns:
    df[col] = df[col].notna()
```

**Comment by ZuzannaKozyra** [comment]
[RedukcjaRamki.zip](https://github.com/adamAfro/hereishouse/files/13851544/RedukcjaRamki.zip)

- Dodałam kolumny z rokiem, miesiącem i dniem
- Zastosowałam to, co jest w komentarzu powyżej
- Zmienne `deposit`, `fence`, `type` usunęłam ze zbioru, bo nie miały żadnych innych wartości niż `NaN`
- Zmienne, które są mało istotne (mają wiele braków) to np. `garret_type` lub `roof_type`, czego nie da się nawet dodać w oddzielnej kolumnie jako dodatkowy atrybut na plus (bo to jest coś, co mało ludzi dodaje w ogłoszeniach, ale przecież każdy dom ma dach), więc nie wiem czy usuwamy, czy tak zostawiamy
- Podczas patrzenia na te dane zauważyłam, że `building_year` i `building_floors_num` są w dziwnym formacie, nie wiem czy tylko u mnie, więc jakbyście mogli sprawdzić

**Comment by adamAfro** [comment]
```py
from pandas import get_dummies

get_dummies(df, columns=['floors_num', 'garret_type', 'roof_type', 'roofing', 'location', 'recreational', 'market', 'building_material', 'building_type', 'building_floors_num', 'rooms_num', 'floor_no', 'windows_type', 'heating', 'construction_status', 'building_ownership'])
```
